redisOperator:
{% if commercial.enabled %}
  imageName: {{commercial.registry.url}}/vanillastack/redis-operator
  imageTag: {{ redis.operator.imagetag }} 
{% else %}
  imageName: quay.io/opstree/redis-operator
  imageTag: {{ redis.operator.imagetag }} 
{% endif %}
  imagePullPolicy: Always
  name: redis-operator
