---
- name: create join token
  command: kubeadm token generate
  register: generated_token
  run_once: true
  # delegate_to: "{{ groups.master[0] }}"

- name: save token
  lineinfile:
    path: /tmp/cluster_vars.yml
    regexp: '^(.*)token:(.*)$'
    line: "token: {{ generated_token.stdout }}"
    create: true

- name: create certificate key
  command: "kubeadm alpha certs certificate-key"
  register: generated_certificate_key
  run_once: true
  # delegate_to: "{{ groups.master[0] }}"

- name: save certificate key
  lineinfile:
    path: /tmp/cluster_vars.yml
    regexp: '^(.*)certificate_key(.*)$'
    line: "certificate_key: {{ generated_certificate_key.stdout }}"
    create: true

- name: Store vars localy
  fetch:
    src: /tmp/cluster_vars.yml
    dest: /tmp/
    flat: true
