---
- name: Include certificate var
  include_vars:
    file: /tmp/cluster_vars.yml
  when: certificate_key is not defined or certificate_key|length <1

- name: define port, kubelet is listening on
  set_fact:
    apiport: "{% if global.externalLB %}6443{% else %}8443{% endif %}"

- name: Init Cluster
  command: > 
    kubeadm init --service-cidr {{ kubernetes.service_cidr }} \
                 --token {{ token }} --node-name {{ inventory_hostname_short }} \
                 {% if global.isHA %}
                 --control-plane-endpoint api.{{ kubernetes.loadBalancer.clusterDomain }}:6443 \
                 {% endif %}
                 --upload-certs \
                 --apiserver-bind-port {{ apiport }} \
                 --certificate-key {{ certificate_key }} \
                 --ignore-preflight-errors=Port-6443 \
                 {% if ansible_distribution != 'Debian' %}
                 --skip-phases=addon/kube-proxy \
                 {% endif %}
                 {% if ansible_os_family == 'Suse' and commercial.enabled != true %}
                 --image-repository k8s.gcr.io --kubernetes-version latest \
                 {% endif %}
                 {% if commercial.enabled %}
                 --image-repository {{commercial.registry.url}}/vanillastack --kubernetes-version latest \
                 {% endif %}
                 {{ kubernetes.kubeadm_opts }} \
                 {{ kubernetes.init_opts }}
  register: init_cluster
