---
- name: create folder
  file: 
    path: "{{ ansible_env.HOME }}/{{ item }}/"
    state: directory
    mode: '750'
    owner: "{{ ansible_env.USER }}"
  loop:
    - .kube

- name: Copy admin.conf to Home directory
  become: true
  copy:
    src: "{{ kubernetes.kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    remote_src: true

- name: fetch kubeadm config
  become: true
  fetch:
    src: "{{ kubernetes.kubeadmin_config }}"
    dest: "/tmp/ansible/{{ global.uuid }}/"
    flat: true

- name: refresh repo
  command: helm repo update

- name: Deploy latest version of Cilium
  community.kubernetes.helm:
    name: cilium
    chart_ref: vanillastack/cilium
    release_namespace: kube-system
    values: "{{ lookup('template', 'cilium-values.yaml.j2') | from_yaml }}"
    create_namespace: true
    wait: true
  when: ansible_os_family == 'Suse' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Ubuntu'

- name: Deploy latest version of Cilium
  community.kubernetes.helm:
    name: cilium
    chart_ref: vanillastack/cilium
    release_namespace: kube-system
    values: "{{ lookup('template', 'cilium-values-debian.yaml.j2') | from_yaml }}"
    create_namespace: true
    wait: true
  when: ansible_distribution == 'Debian'

- name: save vars to kubeconfig
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cluster-config
        namespace: kube-system
      data:
        clusterConfig: |
          {{ hostvars[inventory_hostname] | to_json }}

### To get running config, execute 
### kubectl get -n kube-system cm cluster-config -o=jsonpath='{.data.clusterConfig}' | jq
          
- name: Wait for control-plane pods become ready
  command: "kubectl wait --namespace=kube-system --for=condition=Ready pods --all --timeout=600s"

- name: restart kubedns
  command: kubectl delete po -n kube-system -l k8s-app=kube-dns
