---
- name: enable auto completion
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc" 
    line: "source <(kubectl completion bash)"
    state: present

- name: label worker nodes
  command: >
    kubectl label nodes "{{ item }}" node-role.kubernetes.io/worker=worker \
    openstack-control-plane=enabled openvswitch=enabled linuxbridge=enabled \
    ceph-rgw=enabled openstack-helm-node-class=primary
  with_items:
  - "{{ groups['worker'] }}"
  ignore_errors: true

- name: label storage nodes
  command: kubectl label nodes "{{ item }}" rook=enabled
  with_items:
  - "{{ groups['storage'] }}"
  ignore_errors: true

- name: label compute node
  command: kubectl label nodes "{{ item }}" openstack-compute-node=enabled
  with_items:
  - "{{ groups['compute'] }}"
  ignore_errors: true
- name: manage access creds
  block:
  - name: copy ssh key to master1
    copy: 
      src: "{{ ansible_ssh_private_key_file }}"
      dest: /tmp/tempkey.pem
  
  - name: add ssh key as secret
    command: >
      kubectl create secret generic --namespace kube-system management-ssh-key --from-file=id_rsa=/tmp/tempkey.pem
  
  - name: make sure, ssh key is removed
    file:
      path: /tmp/tempkey.pem
      state: absent
  when: ansible_ssh_private_key_file is defined and ansible_ssh_private_key_file|length>0

