---
- name: Wait for nodes
  hosts: kube_cluster
  become: false
  gather_facts: no
  roles:
    - role: wait-for-nodes

- name: Secure Servers (Installing Polyverse)
  hosts: kube_cluster
  become: true
  gather_facts: true
  roles:
    - role: deploy-polyverse
      when: polyverse.enabled
 
- name: Configure Servers
  hosts: kube_cluster
  become: true
  gather_facts: true
  roles:
    - role: deploy-kubernetes
      action: 01_configure_systems

- name: Install Keepalived
  hosts: haproxy[0]
  become: true
  gather_facts: true
  vars:
    keepalived_MASTER_SLAVE: MASTER
    keepalived_priority: 110
  roles:
    - role: install-haproxy
      action: 01_install_keepalived
      when: not global.externalLB and global.isHA

- name: Install Keepalived
  hosts: haproxy[1:]
  become: true
  roles:
    - role: install-haproxy
      action: 01_install_keepalived
      when: not global.externalLB and global.isHA

- name: Install HaProxy
  hosts: master
  become: true
  gather_facts: true
  roles:
    - role: install-haproxy
      action: 02_install_haproxy
      when: not global.externalLB

- name: Configure Kube Systems
  hosts: kube_cluster
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 02_configure_cluster

- name: generate secrets
  hosts: master[0]
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 02-1-generate-certificate

- name: Init KubeCluster
  hosts: master[0]
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 03_deploy_kubernetes

- name: Add Master to KubeCluster
  hosts: master[1:]
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 04_add_nodes

- name: Add worker to KubeCluster
  hosts: worker
  become: true
  gather_facts: no
  roles:
    - role: deploy-kubernetes
      action: 05_add_worker

- name: create folder for config
  hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: make sure local uuid directory exists
      file:
        state: directory
        path: "/tmp/ansible/{{ global.uuid }}"
        recurse: yes

- name: Deploy Networking
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
    - role: deploy-kubernetes
      action: 06_configure_network

- name: Label Nodes
  hosts: master[0]
  gather_facts: yes
  roles:
    - role: deploy-kubernetes
      action: 07_label_nodes

- name: Deploy Nginx-Ingress
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: prepare-registry
      when: ingress.enabled
    - role: helm-nginx-ingress
      when: ingress.enabled

- name: Deploy Rook
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: prepare-registry
    - role: deploy-rook

- name: Deploy Cert Manager
  hosts: master[0]
  become: false
  gather_facts: true
  roles:
    - role: prepare-registry
      when: certmanager.enabled
    - role: helm-cert-manager
      when: certmanager.enabled

- name: Deploy OpenStack
  hosts: master[0]
  become: false
  gather_facts: no
  roles:
    - role: prepare-registry
      when: openstack.enabled
    - role: deploy-openstack
      when: openstack.enabled

- name: install K8S Dashboard
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: kubernetes.dashboard.enabled
    - role: install-kubedashboard
      when: kubernetes.dashboard.enabled

- name: Deploy cloudfoundry
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: stratos.enabled
    - role: install-cloudfoundry
      when: cloudfoundry.enabled

- name: install stratos
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: stratos.enabled
    - role: install-stratos
      when: stratos.enabled

- name: Deploy efk
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: efkstack.enabled
    - role: install-efk
      action: init
      when: efkstack.enabled
    - role: install-efk
      action: es_deploy
      when: efkstack.enabled
    - role: install-efk
      action: kibana_deploy
      when: efkstack.enabled
    - role: install-efk
      action: "{{ efkstack.logaggregator.name }}_deploy"
      when: efkstack.enabled

- name: Deploy Postgres Operator
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: guacamole.enabled
    - role: deploy-postgres-operator
      when: postgresOperator.enabled

- name: install guacamole
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: guacamole.enabled
    - role: install-guacamole
      when: guacamole.enabled

- name: Deploy Harbor
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: harbor.enabled
    - role: deploy-harbor
      when: harbor.enabled

- name: Deploy KubeVirt
  hosts: master[0]
  become: false
  gather_facts: false
  roles:
    - role: prepare-registry
      when: kubevirt.enabled
    - role: deploy-kubevirt
      action: operator
      when: kubevirt.enabled

- name: Deploy KubeVirt CLI
  hosts: master[0]
  become: true
  gather_facts: false
  roles:
    - role: deploy-kubevirt
      action: virtctl
      when: kubevirt.enabled

- name: install moodle
  hosts: master[0]
  gather_facts: true
  roles:
    - role: prepare-registry
      when: moodle.enabled
    - role: install-moodle
      when: moodle.enabled

- name: install monitoring
  hosts: master[0]
  gather_facts: true
  roles:
  - role: install-monitoring
    action: operator
    when: prometheus.enabled
- name: install redis cluster
  hosts: master[0]
  gather_facts: false
  roles:
  - role: install-redis-operator
    when: redis.enabled
  - role: install-redis-cluster
    when: redis.enabled
